// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw_a_86ytUDDdfv1q1IVlcTgir3ItnD-E',
    appId: '1:1054148070771:web:0345ae39ee574fe003c906',
    messagingSenderId: '1054148070771',
    projectId: 'kualitas-udara-efd77',
    authDomain: 'kualitas-udara-efd77.firebaseapp.com',
    databaseURL: 'https://kualitas-udara-efd77-default-rtdb.firebaseio.com',
    storageBucket: 'kualitas-udara-efd77.appspot.com',
    measurementId: 'G-CQ31MCLJ4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6qenlceYgN7vl29yk1wflHcxOm9Ee_wA',
    appId: '1:1054148070771:android:afa7ece213d70c5303c906',
    messagingSenderId: '1054148070771',
    projectId: 'kualitas-udara-efd77',
    databaseURL: 'https://kualitas-udara-efd77-default-rtdb.firebaseio.com',
    storageBucket: 'kualitas-udara-efd77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH3jMh2yeY9ja2Biso2z259aVq3dXEO04',
    appId: '1:1054148070771:ios:01b979fd23024cea03c906',
    messagingSenderId: '1054148070771',
    projectId: 'kualitas-udara-efd77',
    databaseURL: 'https://kualitas-udara-efd77-default-rtdb.firebaseio.com',
    storageBucket: 'kualitas-udara-efd77.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH3jMh2yeY9ja2Biso2z259aVq3dXEO04',
    appId: '1:1054148070771:ios:ed7eb81169e23ceb03c906',
    messagingSenderId: '1054148070771',
    projectId: 'kualitas-udara-efd77',
    databaseURL: 'https://kualitas-udara-efd77-default-rtdb.firebaseio.com',
    storageBucket: 'kualitas-udara-efd77.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
